name: featureX Branch - Base Pipeline

on:
    push:
        branches:
        - 'featureX'

jobs:

    Build:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checking Out Code Repo
              uses: actions/checkout@v2

            # Clean output directory
            - name: Clean Output Directory
              working-directory: ./app
              run: mvn -B clean

            #Setting Java
            - name: Set up JDK 8
              uses: actions/setup-java@v2
              with:
                java-version: '8'
                distribution: 'temurin'

            # Build the project by using Maven
            - name: Build with Maven
              working-directory: ./app
              run: mvn -B package --file pom.xml

            # Publishing artifacts
            - name: Step 3 - Use the Upload Artifact GitHub Action
              uses: actions/upload-artifact@v3
              with: 
                name: MyBuiltArtifact
                path: ./app/target/verademo.war

    VeracodePipelineScan:
        needs: Build
        uses: ./.github/workflows/VeracodePipelineScan.yml
        secrets: inherit

    Test:
        needs: Build
        runs-on: ubuntu-latest
        steps:
            - name: CMD Test
              run: |
                ls -all
  